# MLK-CU01-040-060 core, XCKU060-FFVA1156.
# Pin source: core schematic 20211012, page 6 (banks 66/67/68).
# DDR4 A14/A15/A16 share WE_N/CAS_N/RAS_N respectively.
# The generated DDR4 IP XDC supplies the 100 MHz clock and PHY timing.
# AXI ports are internal fabric interfaces: connect them in the block design.

set_property -dict {PACKAGE_PIN D10 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[0]}]
set_property -dict {PACKAGE_PIN C8 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[1]}]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[2]}]
set_property -dict {PACKAGE_PIN D9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[3]}]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[4]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[5]}]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[6]}]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[7]}]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[8]}]
set_property -dict {PACKAGE_PIN F10 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[9]}]
set_property -dict {PACKAGE_PIN G9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[10]}]
set_property -dict {PACKAGE_PIN J9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[11]}]
set_property -dict {PACKAGE_PIN F9 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[12]}]
set_property -dict {PACKAGE_PIN J8 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[13]}]
set_property -dict {PACKAGE_PIN G10 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[14]}]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[15]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[16]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[17]}]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[18]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[19]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[20]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[21]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[22]}]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[23]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[24]}]
set_property -dict {PACKAGE_PIN L12 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[25]}]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[26]}]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[27]}]
set_property -dict {PACKAGE_PIN K12 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[28]}]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[29]}]
set_property -dict {PACKAGE_PIN G12 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[30]}]
set_property -dict {PACKAGE_PIN K11 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[31]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[32]}]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[33]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[34]}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[35]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[36]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[37]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[38]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[39]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[40]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[41]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[42]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[43]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[44]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[45]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[46]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[47]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[48]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[49]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[50]}]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[51]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[52]}]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[53]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[54]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[55]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[56]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[57]}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[58]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[59]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[60]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[61]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[62]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dq[63]}]
set_property -dict {PACKAGE_PIN F8 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[0]}]
set_property -dict {PACKAGE_PIN L8 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[1]}]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[2]}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[3]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[4]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[5]}]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[6]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD POD12_DCI} [get_ports {C0_DDR4_0_dm_n[7]}]
set_property -dict {PACKAGE_PIN A29 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[0]}]
set_property -dict {PACKAGE_PIN E26 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[1]}]
set_property -dict {PACKAGE_PIN B29 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[2]}]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[3]}]
set_property -dict {PACKAGE_PIN C28 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[4]}]
set_property -dict {PACKAGE_PIN B26 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[5]}]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[6]}]
set_property -dict {PACKAGE_PIN C27 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[7]}]
set_property -dict {PACKAGE_PIN E27 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[8]}]
set_property -dict {PACKAGE_PIN F27 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[9]}]
set_property -dict {PACKAGE_PIN A28 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[10]}]
set_property -dict {PACKAGE_PIN E28 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[11]}]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[12]}]
set_property -dict {PACKAGE_PIN D28 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[13]}]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_ba[0]}]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_ba[1]}]
set_property -dict {PACKAGE_PIN D25 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_bg[0]}]
set_property -dict {PACKAGE_PIN D24 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[14]}]
set_property -dict {PACKAGE_PIN A25 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[15]}]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_adr[16]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[0]}]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[0]}]
set_property -dict {PACKAGE_PIN K10 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[1]}]
set_property -dict {PACKAGE_PIN J10 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[1]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[2]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[2]}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[3]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[3]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[4]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[4]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[5]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[5]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[6]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[6]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_t[7]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD DIFF_POD12_DCI} [get_ports {C0_DDR4_0_dqs_c[7]}]
set_property -dict {PACKAGE_PIN B27 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_act_n}]
set_property -dict {PACKAGE_PIN F24 IOSTANDARD LVCMOS12} [get_ports {C0_DDR4_0_reset_n}]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {C0_DDR4_0_ck_t[0]}]
set_property -dict {PACKAGE_PIN A24 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {C0_DDR4_0_ck_c[0]}]
set_property -dict {PACKAGE_PIN C23 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_cke[0]}]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_cs_n[0]}]
set_property -dict {PACKAGE_PIN A27 IOSTANDARD SSTL12_DCI} [get_ports {C0_DDR4_0_odt[0]}]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD DIFF_SSTL12} [get_ports {C0_SYS_CLK_0_clk_p}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD DIFF_SSTL12} [get_ports {C0_SYS_CLK_0_clk_n}]

# MLK-H4 PCIe x8: base schematic page 11, core banks 226/227.
# XDMA X0Y1 internally maps lane0 to GT227 CH3 (X1Y15).
# Match connector lane numbering directly; do not reverse again in RTL/XDC.
set_property PACKAGE_PIN F2 [get_ports {pcie_7x_mgt_rtl_0_rxp[0]}]
set_property PACKAGE_PIN H2 [get_ports {pcie_7x_mgt_rtl_0_rxp[1]}]
set_property PACKAGE_PIN K2 [get_ports {pcie_7x_mgt_rtl_0_rxp[2]}]
set_property PACKAGE_PIN M2 [get_ports {pcie_7x_mgt_rtl_0_rxp[3]}]
set_property PACKAGE_PIN P2 [get_ports {pcie_7x_mgt_rtl_0_rxp[4]}]
set_property PACKAGE_PIN T2 [get_ports {pcie_7x_mgt_rtl_0_rxp[5]}]
set_property PACKAGE_PIN V2 [get_ports {pcie_7x_mgt_rtl_0_rxp[6]}]
set_property PACKAGE_PIN Y2 [get_ports {pcie_7x_mgt_rtl_0_rxp[7]}]
set_property PACKAGE_PIN F1 [get_ports {pcie_7x_mgt_rtl_0_rxn[0]}]
set_property PACKAGE_PIN H1 [get_ports {pcie_7x_mgt_rtl_0_rxn[1]}]
set_property PACKAGE_PIN K1 [get_ports {pcie_7x_mgt_rtl_0_rxn[2]}]
set_property PACKAGE_PIN M1 [get_ports {pcie_7x_mgt_rtl_0_rxn[3]}]
set_property PACKAGE_PIN P1 [get_ports {pcie_7x_mgt_rtl_0_rxn[4]}]
set_property PACKAGE_PIN T1 [get_ports {pcie_7x_mgt_rtl_0_rxn[5]}]
set_property PACKAGE_PIN V1 [get_ports {pcie_7x_mgt_rtl_0_rxn[6]}]
set_property PACKAGE_PIN Y1 [get_ports {pcie_7x_mgt_rtl_0_rxn[7]}]
set_property PACKAGE_PIN G4 [get_ports {pcie_7x_mgt_rtl_0_txp[0]}]
set_property PACKAGE_PIN J4 [get_ports {pcie_7x_mgt_rtl_0_txp[1]}]
set_property PACKAGE_PIN L4 [get_ports {pcie_7x_mgt_rtl_0_txp[2]}]
set_property PACKAGE_PIN N4 [get_ports {pcie_7x_mgt_rtl_0_txp[3]}]
set_property PACKAGE_PIN R4 [get_ports {pcie_7x_mgt_rtl_0_txp[4]}]
set_property PACKAGE_PIN U4 [get_ports {pcie_7x_mgt_rtl_0_txp[5]}]
set_property PACKAGE_PIN W4 [get_ports {pcie_7x_mgt_rtl_0_txp[6]}]
set_property PACKAGE_PIN AA4 [get_ports {pcie_7x_mgt_rtl_0_txp[7]}]
set_property PACKAGE_PIN G3 [get_ports {pcie_7x_mgt_rtl_0_txn[0]}]
set_property PACKAGE_PIN J3 [get_ports {pcie_7x_mgt_rtl_0_txn[1]}]
set_property PACKAGE_PIN L3 [get_ports {pcie_7x_mgt_rtl_0_txn[2]}]
set_property PACKAGE_PIN N3 [get_ports {pcie_7x_mgt_rtl_0_txn[3]}]
set_property PACKAGE_PIN R3 [get_ports {pcie_7x_mgt_rtl_0_txn[4]}]
set_property PACKAGE_PIN U3 [get_ports {pcie_7x_mgt_rtl_0_txn[5]}]
set_property PACKAGE_PIN W3 [get_ports {pcie_7x_mgt_rtl_0_txn[6]}]
set_property PACKAGE_PIN AA3 [get_ports {pcie_7x_mgt_rtl_0_txn[7]}]
set_property PACKAGE_PIN P6 [get_ports {diff_clock_rtl_0_clk_p[0]}]
set_property PACKAGE_PIN P5 [get_ports {diff_clock_rtl_0_clk_n[0]}]
create_clock -name pcie_refclk -period 10.000 [get_ports {diff_clock_rtl_0_clk_p[0]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33 PULLUP true} [get_ports reset_rtl_0]
set_false_path -from [get_ports reset_rtl_0]
# Core configuration bank: CFGBVS tied to VCCO=3.3 V.
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
