# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/xdma_pcie_ddr4_0_2.xci
# IP: The module: 'xdma_pcie_ddr4_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_0/xdma_pcie_ddr4_0_2_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs || ORIG_REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs} -quiet] -quiet

# Block Designs: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/bd_8c6a.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a || ORIG_REF_NAME==bd_8c6a} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_0/bd_8c6a_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_microblaze_I_0 || ORIG_REF_NAME==bd_8c6a_microblaze_I_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_1/bd_8c6a_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_rst_0_0 || ORIG_REF_NAME==bd_8c6a_rst_0_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_2/bd_8c6a_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_ilmb_0 || ORIG_REF_NAME==bd_8c6a_ilmb_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_3/bd_8c6a_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_dlmb_0 || ORIG_REF_NAME==bd_8c6a_dlmb_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_4/bd_8c6a_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_dlmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_5/bd_8c6a_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_ilmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_6/bd_8c6a_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_lmb_bram_I_0 || ORIG_REF_NAME==bd_8c6a_lmb_bram_I_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_7/bd_8c6a_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_second_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_8/bd_8c6a_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_second_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_9/bd_8c6a_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_8c6a_second_lmb_bram_I_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_10/bd_8c6a_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_iomodule_0_0 || ORIG_REF_NAME==bd_8c6a_iomodule_0_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_1/xdma_pcie_ddr4_0_2_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_pcie_ddr4_0_2_phy || ORIG_REF_NAME==xdma_pcie_ddr4_0_2_phy} -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_0/bd_8c6a_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_microblaze_I_0 || ORIG_REF_NAME==bd_8c6a_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_0/bd_8c6a_microblaze_I_0_ooc_debug.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_1/bd_8c6a_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_rst_0_0 || ORIG_REF_NAME==bd_8c6a_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_1/bd_8c6a_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_rst_0_0 || ORIG_REF_NAME==bd_8c6a_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_2/bd_8c6a_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_ilmb_0 || ORIG_REF_NAME==bd_8c6a_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_3/bd_8c6a_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_dlmb_0 || ORIG_REF_NAME==bd_8c6a_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_6/bd_8c6a_lmb_bram_I_0_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_9/bd_8c6a_second_lmb_bram_I_0_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_10/bd_8c6a_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_iomodule_0_0 || ORIG_REF_NAME==bd_8c6a_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/bd_8c6a_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_0/xdma_pcie_ddr4_0_2_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs || ORIG_REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_0/xdma_pcie_ddr4_0_2_microblaze_mcs_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_1/par/xdma_pcie_ddr4_0_2_phy_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/xdma_pcie_ddr4_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_pcie_ddr4_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/par/xdma_pcie_ddr4_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_pcie_ddr4_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/xdma_pcie_ddr4_0_2.xci
# IP: The module: 'xdma_pcie_ddr4_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_0/xdma_pcie_ddr4_0_2_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs || ORIG_REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs} -quiet] -quiet

# Block Designs: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/bd_8c6a.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a || ORIG_REF_NAME==bd_8c6a} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_0/bd_8c6a_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_microblaze_I_0 || ORIG_REF_NAME==bd_8c6a_microblaze_I_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_1/bd_8c6a_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_rst_0_0 || ORIG_REF_NAME==bd_8c6a_rst_0_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_2/bd_8c6a_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_ilmb_0 || ORIG_REF_NAME==bd_8c6a_ilmb_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_3/bd_8c6a_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_dlmb_0 || ORIG_REF_NAME==bd_8c6a_dlmb_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_4/bd_8c6a_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_dlmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_5/bd_8c6a_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_ilmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_6/bd_8c6a_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_lmb_bram_I_0 || ORIG_REF_NAME==bd_8c6a_lmb_bram_I_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_7/bd_8c6a_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_second_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_8/bd_8c6a_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_8c6a_second_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_9/bd_8c6a_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_8c6a_second_lmb_bram_I_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_10/bd_8c6a_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8c6a_iomodule_0_0 || ORIG_REF_NAME==bd_8c6a_iomodule_0_0} -quiet] -quiet

# IP: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_1/xdma_pcie_ddr4_0_2_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_pcie_ddr4_0_2_phy || ORIG_REF_NAME==xdma_pcie_ddr4_0_2_phy} -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_0/bd_8c6a_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_microblaze_I_0 || ORIG_REF_NAME==bd_8c6a_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_0/bd_8c6a_microblaze_I_0_ooc_debug.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_1/bd_8c6a_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_rst_0_0 || ORIG_REF_NAME==bd_8c6a_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_1/bd_8c6a_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_rst_0_0 || ORIG_REF_NAME==bd_8c6a_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_2/bd_8c6a_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_ilmb_0 || ORIG_REF_NAME==bd_8c6a_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_3/bd_8c6a_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_dlmb_0 || ORIG_REF_NAME==bd_8c6a_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_6/bd_8c6a_lmb_bram_I_0_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_9/bd_8c6a_second_lmb_bram_I_0_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/ip/ip_10/bd_8c6a_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8c6a_iomodule_0_0 || ORIG_REF_NAME==bd_8c6a_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/bd_0/bd_8c6a_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_0/xdma_pcie_ddr4_0_2_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs || ORIG_REF_NAME==xdma_pcie_ddr4_0_2_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_0/xdma_pcie_ddr4_0_2_microblaze_mcs_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/ip_1/par/xdma_pcie_ddr4_0_2_phy_ooc.xdc

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/xdma_pcie_ddr4_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_pcie_ddr4_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FPGA_Doc/project_PCIE/project_PCIE.srcs/sources_1/bd/xdma_pcie/ip/xdma_pcie_ddr4_0_2/par/xdma_pcie_ddr4_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_pcie_ddr4_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
